apiVersion: v1
kind: Template
parameters:
- name: PROJECT_ID
  required: true
- name: COMPONENT_ID
  required: true
- name: BITBUCKET_URL
  required: true
- name: QUICKSTARTER
  required: true
- name: PIPELINE_POSTFIX
  required: true
- name: ODS_GIT_REF_SHARED_LIBRARY
  required: true
- name: ODS_GIT_REF_QUICKSTARTER
  required: true
- name: ODS_IMAGE_TAG
  required: true
- name: QUICKSTARTER_REPO
  required: true
- name: GROUP_ID
  required: true
- name: PACKAGE_NAME
  required: true
- name: ODS_NAMESPACE
  required: true
- name: ODS_BB_PROJECT
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ods-quickstarters-${QUICKSTARTER}-${PIPELINE_POSTFIX}
    namespace: ${PROJECT_ID}-cd
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${ODS_GIT_REF_QUICKSTARTER}
        uri: ${BITBUCKET_URL}/scm/${ODS_BB_PROJECT}/${QUICKSTARTER_REPO}.git
      sourceSecret:
        name: cd-user-with-password
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        env:
          - name: PROJECT_ID
            value: ${PROJECT_ID}
          - name: COMPONENT_ID
            value: ${COMPONENT_ID}
          - name: GROUP_ID
            value: ${GROUP_ID}
          - name: PACKAGE_NAME
            value: ${PACKAGE_NAME}
          - name: GIT_URL_HTTP
            value: ${BITBUCKET_URL}/scm/${PROJECT_ID}/${PROJECT_ID}-${COMPONENT_ID}.git
          - name: ODS_IMAGE_TAG
            value: ${ODS_IMAGE_TAG}
          - name: ODS_GIT_REF
            value: ${ODS_GIT_REF_SHARED_LIBRARY}
          - name: ODS_NAMESPACE
            value: ${ODS_NAMESPACE}
        jenkinsfilePath: ${QUICKSTARTER}/Jenkinsfile
      type: JenkinsPipeline
    triggers: []
